// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAVHRiRBs-4HRoAycck4ysjqGRqyNcEfsc',
    appId: '1:929175971803:web:0a043d7e18584e1ad769fe',
    messagingSenderId: '929175971803',
    projectId: 'my-event-app-d2ca0',
    authDomain: 'my-event-app-d2ca0.firebaseapp.com',
    storageBucket: 'my-event-app-d2ca0.firebasestorage.app',
    measurementId: 'G-Q2ED8T63SG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBZynfd0FzgjWpaHZpCci_C8y9NcDXtfq8',
    appId: '1:929175971803:android:5587fdda6c1ba13dd769fe',
    messagingSenderId: '929175971803',
    projectId: 'my-event-app-d2ca0',
    storageBucket: 'my-event-app-d2ca0.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAm-yJYisXp4W-CyCp2ijmR3kkozcHMRt4',
    appId: '1:929175971803:ios:3014cb02fb0a1cd1d769fe',
    messagingSenderId: '929175971803',
    projectId: 'my-event-app-d2ca0',
    storageBucket: 'my-event-app-d2ca0.firebasestorage.app',
    iosClientId: '929175971803-vvdjhi85n777dn0a0bvc4s8ug79hhht5.apps.googleusercontent.com',
    iosBundleId: 'com.example.myEventApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAm-yJYisXp4W-CyCp2ijmR3kkozcHMRt4',
    appId: '1:929175971803:ios:3014cb02fb0a1cd1d769fe',
    messagingSenderId: '929175971803',
    projectId: 'my-event-app-d2ca0',
    storageBucket: 'my-event-app-d2ca0.firebasestorage.app',
    iosClientId: '929175971803-vvdjhi85n777dn0a0bvc4s8ug79hhht5.apps.googleusercontent.com',
    iosBundleId: 'com.example.myEventApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAVHRiRBs-4HRoAycck4ysjqGRqyNcEfsc',
    appId: '1:929175971803:web:62ea09684476a2d6d769fe',
    messagingSenderId: '929175971803',
    projectId: 'my-event-app-d2ca0',
    authDomain: 'my-event-app-d2ca0.firebaseapp.com',
    storageBucket: 'my-event-app-d2ca0.firebasestorage.app',
    measurementId: 'G-PJ790QSPDE',
  );

}